[package]
name = "Practice-api"
version = "0.1.0"
edition = "2021"

[dependencies]
    axum = "0.8.6"
dotenvy = "0.15"
futures = "0.3.31"
mongodb = "3.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
uuid = "1.18.1"
